### ISSUE TITLE
我尝试根据README进行复现，出现了以下问题。

### ISSUE THREAD

**Issue by LiYuXuan1999** [CVIU-CSU/M2MRF-Lesion-Segmentation#10]
![Snipaste_2024-02-23_15-53-16](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/assets/57089190/452e31f5-aedf-4a57-8a30-e105e2770e54)

所有的数据都准备好了，并进行了增强。

但是我只有单卡进行训练，不知如何改进。

**Comment by haotianll** [comment]
Hi, could you please share your environment information or the full running log?

**Comment by LiYuXuan1999** [comment]
2024-02-26 12:53:19,293 - mmseg - INFO - workflow: [('train', 1)], max: 40000 iters
2024-02-26 12:53:19,293 - mmseg - INFO - Checkpoints will be saved to /home/dell/disk4/dell/Liwang/M2MRF-Lesion-Segmentation/work_dirs/fcn_hr48-M2MRF-C_40k_idrid_bdice by HardDiskBackend.
2024-02-26 12:53:31,833 - mmcv - INFO - Reducer buckets have been rebuilt in this iteration.
2024-02-26 12:54:11,177 - mmseg - INFO - Iter [50/40000]	lr: 9.989e-03, eta: 11:29:39, time: 1.036, data_time: 0.141, memory: 12088, decode.loss_seg: 1.0000, decode.acc_seg: 1.1453, loss: 1.0000
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 157, in main
    meta=meta)
  File "/home/dell/disk4/dell/Liwang/M2MRF-Lesion-Segmentation/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 59, in train
    data_batch = next(data_loader)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 32, in __next__
    data = next(self.iter_loader)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
PIL.UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dell/disk4/dell/Liwang/M2MRF-Lesion-Segmentation/mmseg/datasets/custom.py", line 190, in __getitem__
    return self.prepare_train_img(idx)
  File "/home/dell/disk4/dell/Liwang/M2MRF-Lesion-Segmentation/mmseg/datasets/custom.py", line 207, in prepare_train_img
    return self.pipeline(results)
  File "/home/dell/disk4/dell/Liwang/M2MRF-Lesion-Segmentation/mmseg/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/dell/disk4/dell/Liwang/M2MRF-Lesion-Segmentation/mmseg/datasets/pipelines/loading.py", line 134, in __call__
    backend=self.imdecode_backend).squeeze().astype(np.uint8)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/mmcv/image/io.py", line 247, in imfrombytes
    img = Image.open(buff)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/PIL/Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f62d83aa9b0>

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11909) of binary: /home/dell/anaconda3/envs/m2mrf/bin/python
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dell/anaconda3/envs/m2mrf/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-26_12:54:44
  host      : dell-PowerEdge-R740
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11909)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

这是最新的输出日志，我尝试在单卡上进行训练。
命令为CUDA_VISIBLE_DEVICES=0 PORT=12345 tools/dist_train.sh configs/m2mrf/fcn_hr48-M2MRF-C_40k_idrid_bdice.py 1
GPT告诉我在数据加载过程中再次出现了无法识别的图像文件。
您认为这是由于单卡训练引起的error吗？

**Comment by LiYuXuan1999** [comment]
需要将数据集下的EX、HE、MA、SE中的.tif文件转换为.jpg或.png吗？

**Comment by haotianll** [comment]
你可以先试一下根据这个脚本来做一下预处理 [prepare_labels.py](https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/blob/master/tools/prepare_labels.py)，再确认一下 mmcv 的版本是否一致。

**Comment by LiYuXuan1999** [comment]
做了预处理的，为了使用cuda，mmcv换成了1.4.2，命令如下。代码中的mmcv版本限制改到了1.4.2.
pip install mmcv-full==1.4.2 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html

**Comment by haotianll** [comment]
我不确定mmcv的版本是否有影响，关于数据预处理，请提供一下您的邮箱，我可以告诉更多的细节。

**Comment by LiYuXuan1999** [comment]
没事的，我已经把算子提取出来了。
感谢解答

**Comment by haotianll** [comment]
好的，不客气~

**Comment by LiYuXuan1999** [comment]
这个算子参数量也不小噢！

**Comment by LiYuXuan1999** [comment]
nice

**Comment by WHLWJL** [comment]
请问一下，我根据prapare_labels.py对DDR和IDRID数据集进行预处理时，IDRID生成的annotations里面的图像是全黑的图像，而DDR处理成功，这是什么原因导致的那。希望作者大大回复以下

**Comment by hengdezhu** [comment]
> 我不确定mmcv的版本是否有影响，关于数据预处理，请提供一下您的邮箱，我可以告诉更多的细节。

Hello Haotian, 请问可以告诉我吗？[hengdezhu@gmail.com](mailto:hengdezhu@gmail.com)，我正在复现你们的工作，请跟您请教。Thanks

**Comment by haotianll** [comment]
> > 我不确定mmcv的版本是否有影响，关于数据预处理，请提供一下您的邮箱，我可以告诉更多的细节。
> 
> Hello Haotian, 请问可以告诉我吗？[hengdezhu@gmail.com](mailto:hengdezhu@gmail.com)，我正在复现你们的工作，请跟您请教。Thanks

已发送，请查看邮件
